name: "Lona GitHub Action"
description: "A Github Action to check if Lona can run on the repo and upload a documentation website to Lona."
author: "Mathieu Dutour"
outputs:
  upload_url:
    description: "The URL to upload the docs to."
  lona_organization_id:
    description: "The id of the Lona organization this repo is part of."
  deployment_id:
    description: "The id of the GitHub deployment that was started by this action."
  output_folder:
    description: "The folder that will get deployed to Lona's servers."
inputs:
  github_token:
    description: "Required for Lona to check the permissions."
    required: true
  output_folder:
    description: "The folder that will get deployed to Lona's servers."
    default: "./.output"
  lona_deploy_url:
    description: "The Lona URL where the websites are deployed."
    default: https://lona-public-assets-dev.s3-eu-west-1.amazonaws.com
  lona_api_base_url:
    description: "The Lona API server."
    required: false
    default: https://81q1ce2llf.execute-api.eu-west-1.amazonaws.com/dev
runs:
  using: "node12"
  main: "lib/main.js"
  post: "lib/post.js"
  env:
    WORKFLOW_SUCCEEDED: ${{ success() }}
branding:
  icon: "git-merge"
  color: "red"
