name: "Lona GitHub Action"
description: "A Github Action to check if Lona can run on the repo and upload a documentation website to Lona."
author: "Mathieu Dutour"
outputs:
  output_folder:
    description: "The folder that will get deployed to Lona's servers."
inputs:
  github_token:
    description: "Required for Lona to check the permissions."
    required: true
  workflow_succeeded:
    description: "Required for setting the deployment state."
    required: true
  ref_name:
    description: "The ref to deploy."
    required: false
  output_folder:
    description: "The folder that will get deployed to Lona's servers."
    required: false
    default: "./.output"
  lona_api_base_url:
    description: "The Lona API server."
    required: false
    default: https://api.lona.design/production
runs:
  using: "node12"
  main: "lib/main.js"
  post: "lib/post.js"
  post-if: always()
  # env:
  #   WORKFLOW_SUCCEEDED: ${{ job.status == 'Success' }}
branding:
  icon: "upload-cloud"
  color: "red"
